### ISSUE TITLE
Ass scss package and folder structure

### ISSUE THREAD

**Issue by 2940cristian** [projectunic0rn/edutrack-ui#2]

**Comment by mindofbeholder** [comment]
I've not used scss before. Not sure how to proceed.

**Comment by 2940cristian** [comment]
@mindofbeholder Understandable, I'm going to link you to a video that helped me setup scss for the first time

https://youtu.be/2QaI5ajg4Hw
https://github.com/projectunic0rn/mentorship-ui

I also recommend looking at Mentrship's package.json and file structure of src/assets/scss to get an idea. Notice how we setup the names such as: _filename.scss. We had a single file import all of the other files for readability. 

If it doesn't click after those two let me know and we'll work on setting it up together. Or if you have any questions how to setup the project.

**Comment by 2940cristian** [comment]
Created a test branch showing a small structure/example of how to add scrips to package.json 
https://github.com/projectunic0rn/edutrack-ui/tree/test

Here's the npm package: https://www.npmjs.com/package/node-sass-chokidar

I hope you've worked with npm/node haha otherwise download it here: https://www.npmjs.com/get-npm
